---
# tasks file for lucazz.cifs_server
- name: Installing Samba packages. (CentOS/RHEL)
#RHEL or CentOS
  yum: pkg={{ item }} state=installed
  with_items:
   - samba
   - samba-client
   - samba-common
   - cifs-utils
   - libselinux-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install selinux bindings
  yum: name=libselinux-python state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing Samba packages. (Debian/Ubuntu)
  apt: pkg={{ item }} state=installed
  with_items:
  - samba
  - samba-common
  - cifs-utils
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Setting Samba to start on boot.
  service: name=smb state=started enabled=yes

- name: Writing samba's config file
  template: src=../templates/smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
  - restart smb
